all:
	gcc hw0101.c mystring.c -lm -o hw0101
	gcc hw0102.c insert.c -lm -o hw0102
	gcc hw0103.c abacus.c insert.c -I. -o hw0103
	gcc hw0104.c -o hw0104

clean:
	rm hw0101
	rm hw0102
	rm hw0103
	rm hw0104
