all:
	gcc hw0101.c mystring.c -I./inc -lm -o out/hw0101
	gcc hw0102.c insert.c -I./inc -lm -o out/hw0102
	gcc hw0103.c abacus.c -I./inc insert.c -I. -o out/hw0103
	gcc hw0104.c -I./inc -o out/hw0104
	gcc hw0105.c oop.c -I./inc -lm -o out/hw0105

clean:
	rm -rf out
	mkdir out
